### ISSUE TITLE
index_pi.js is looking for localization files in the wrong place. Therefore throwing errors when the PI is opened...

### ISSUE THREAD

**Issue by krabs-github** [elgatosf/streamdeck-plugintemplate#10]
index_pi.js is looking for localization files in the wrong place. Therefore throwing errors when the PI is opened...
```
Failed to load resource: net::ERR_FILE_NOT_FOUND              /C:/Users/Krabs/AppData/Roaming/Elgato/StreamDeck/Plugins/en.json:1
file:///C:/Users/Krabs/AppData/Roaming/Elgato/StreamDeck/Plugins/en.json 
```
![Screenshot 2021-12-21 150106](https://user-images.githubusercontent.com/78506543/146990658-8098592d-74fb-47a8-8de8-35827385827e.png)

**Comment by tiptronic** [comment]
I don't see this behaviour, if you keep the file-structure in place...
PI looks for localization files 1 folder above `propertyinspector`, which is `../`
Plugin in the same folder as the application `./`

Please check your file-structure...

**Comment by krabs-github** [comment]
Understood, I will move the PI's one directory deeper.

**Comment by tiptronic** [comment]
well - if you use a template, why do you modify file-structure at all? That's how templates work ;)

**Comment by krabs-github** [comment]
I said I moved them one level deeper. I am not the only one who doesn't
like the structure of this template. You are a true dick. No wonder no one
uses this. I was switching to this template at your suggestion, if you
remember correctly. But don't worry. I won't use it and I will make sure
everyone knows even more about your bad attitude including Zack, Vanessa,
and everyone else I can contact at Elgato.
