### ISSUE TITLE
How do we build this?

### ISSUE THREAD

**Issue by fieldju** [elgatosf/streamdeck-plugintemplate#3]
1. How does one go about building this project into the release artifact?
    - Normally in java script land there is a package.json with script commands. ex: `npm run build` or `yarn build`.
2. How do we go about listing our plugins in the app store?

**Comment by fieldju** [comment]
I found what I was looking for here:
https://developer.elgato.com/documentation/stream-deck/sdk/exporting-your-plugin/

might be worth referencing this in the readme:
- https://developer.elgato.com/documentation/stream-deck/sdk/exporting-your-plugin/
- https://developer.elgato.com/documentation/stream-deck/sdk/distribution-on-the-store/

**Comment by fieldju** [comment]
Also releasing this as a NPX installable template might be pretty cool, similar to CRA.

`npm create-stream-deck-plugin com.fieldju.loldeck`

I might take a stab at it with Typescript.

**Comment by tiptronic** [comment]
The plugins don't need a build process. They could even run in 1 self-contained .html file. (The implementation varies on which features you want to have.)

We want to keep the template simple and give *everybody* a quick head-start. 

If you're looking for a deeper npm - integration, you can use one of the available third-pary implementations (e.g. https://github.com/SReject/easy-streamdeck).
